service: serverless-django

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: website.wsgi.application
  pythonRequirements:
    dockerizePip: non-linux

package:
  exclude:
    - node_modules/**
    - env/**

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  memorySize: 512
  timeout: 30

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
